### ISSUE TITLE
关于迭代重建后的清晰度

### ISSUE THREAD

**Issue by caicaizi-c** [CandleHouse/ArtifactReduction#1]
作者你好，我运行了TIGRE toolbox中的例子，但是结果显示出的OS-SART图像要比ASD-POCS产生的图像模糊，看起来边界很朦胧，那为什么说SART重建产生的图片质量要更高呢？

**Comment by CandleHouse** [comment]
迭代重建的精髓是调参，图像不一样可能相同参数重建效果大相径庭
OS-SART变糊的原因可能是 OS 的 blocksize 设置过大（默认20），设置为1 OS-SART 退化为 SART
可以看看这里：https://github.com/CERN/TIGRE/blob/master/MATLAB/Algorithms/OS_SART.m#LL12C30-L12C30

**Comment by caicaizi-c** [comment]
超级感谢！居然这么快就回复了好感动T-T

**Comment by caicaizi-c** [comment]
> 

超级感谢！！！！居然这么快就回复了真的太感动了T-T

**Comment by caicaizi-c** [comment]
> 迭代重建的精髓是调参，图像不一样可能相同参数重建效果大相径庭 OS-SART变糊的原因可能是 OS 的 blocksize 设置过大（默认20），设置为1 OS-SART 退化为 SART 可以看看这里：https://github.com/CERN/TIGRE/blob/master/MATLAB/Algorithms/OS_SART.m#LL12C30-L12C30

那如果是SART重建的话就会比OS-SART模糊吗？

**Comment by CandleHouse** [comment]
根据我的经验，blocksize 越大，OS-SART 重建同时使用的投影块越多，重建越快，图像质量越模糊
较小的 blocksize 可以使得 OS-SART 在时间和重建质量上取得折中效果
blocksize=5~10 可能是一个能使 OS-SART 比较接近于 SART 的取值

**Comment by caicaizi-c** [comment]
> 根据我的经验，blocksize 越大，OS-SART 重建同时使用的投影块越多，重建越快，图像质量越模糊 较小的 blocksize 可以使得 OS-SART 在时间和重建质量上取得折中效果 blocksize=5~10 可能是一个能使 OS-SART 比较接近于 SART 的取值

好的，谢谢，我去试试！
